# 03 Numpy 


## Plan for this lecture

1. Numpy Introduction 

2. Contrast Memory allocation of Array and Python List 

3. Matrix Multiplication and Vectorisation

## Introduction to Numpy 

![numpy_logo](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/320px-NumPy_logo_2020.svg.png)
* Numerical Python (NumPy) is a package full of methods that can perform useful operations on data.  

* NumPy provides a convenient API (Application Programmable Interface) that provides a way to ‘interface’ with / operate on data. 

* It reintroduces types which is more coding but more efficient way to search/sort/store data than the ‘loosely’ typed nature of Python that we’ve seen so far. 

* More documentation available at: https://numpy.org 


## Numpy Arrays vs Python List

* NumPy arrays are different to Python Lists. 

* NumPy arrays reintroduce the ‘typed’ nature of more ‘verbose’ languages (C, C++, Java), where everything is explicitly typed. 

* NumPy arrays operate like arrays from C and Java where they declared to store data of one type (only integers), unlike Python and JS, which can store data of different types. 

* NumPy arrays therefore data is ‘cast’ – floating point numbers to integers, or in some cases – an error is produced (strings to integers).

## Getting started with Numpy

* You'll either need to install this if you're in VSC. 

* OR if you're in Anaconda or Google Colab, you should have access to Numpy already... just need to import it.

`pip install numpy`

`python3 -m pip install -U numpy --user`

In [349]:
import time
import timeit 
import sys

import numpy as np 
np

<module 'numpy' from '/Users/nick/Library/Python/3.9/lib/python/site-packages/numpy/__init__.py'>

In [169]:
l = [1,2.0,"False",False,5,6]
type(l)

list

In [168]:
print(type(l[0]))

<class 'int'>


In [170]:
a = np.array([1,"false",False,2.0,5,6]) 
a


array(['1', 'false', 'False', '2.0', '5', '6'], dtype='<U32')

In [171]:
a[0].nbytes

4

In [166]:
a[0]

np.int64(1)

## Type of data

* NumPy Arrays are homogeneous, meaning all elements are of the same data type. This uniformity allows for more efficient storage and computation.

* Python Lists are heterogeneous, capable of storing elements of different data types, which adds overhead to manage type information.

## Heterogeneous vs Homogeneous data

* `numpy.array` stores hetrogeneous data (same type) - for memory allocation

* `list` can store homogeneous data (different types) - as point to objects - flexible size.

Notice below how one floating point number will upcast all the integers to floats

In [172]:
a = np.array([3.14,2,3,4,5]) 
a


array([3.14, 2.  , 3.  , 4.  , 5.  ])

In [173]:
py_list = [0, 1.0, "N", True]
py_list

[0, 1.0, 'N', True]

In [176]:
a = np.array([0, 1.0, 2.2, False])
a

array([0. , 1. , 2.2, 0. ])

In [178]:
a[3].dtype

dtype('float64')

In [179]:
a = np.array([1,2,3],dtype='float32')
a


array([1., 2., 3.], dtype=float32)

In [180]:
a[0].dtype

dtype('float32')

In [182]:
a = np.array([1,2,3],dtype='float16')
a

array([1., 2., 3.], dtype=float16)

In [183]:
a[0].dtype

dtype('float16')

## Python's memory overhead 

* Python objects have significant internal overhead due to reference counting, type information, and dynamic memory allocation.

* `Integer` (28 bytes): The integer 42 is stored as a <b>Python object</b>, including the overhead for reference counting and type information, even though the actual value only requires a few bytes.

* `List` (80 bytes): The `list` object itself has overhead, and Python typically over-allocates memory to allow for efficient growth. The actual data stored in the `list` (the integer objects 1, 2, and 3) are not included in the size reported by `sys.getsizeof()`. Each of those elements has its own overhead.

* `String` (54 bytes): Like `lists`, `strs` in Python are objects with associated metadata, even though the actual `str` content is small.

In [184]:
import sys

In [185]:
a = np.array([1,2,3],dtype='float32')
a


array([1., 2., 3.], dtype=float32)

In [186]:
a.nbytes

12

In [64]:
i = 0
for x in a:
    print(x, ":", a[i].nbytes)
    i += 1

1.0 : 4
2.0 : 4
3.0 : 4


In [187]:
sys.getsizeof(a)

124

In [188]:
i = 0
for x in a:
    print(x, ":", sys.getsizeof(a[i]))
    i += 1

1.0 : 28
2.0 : 28
3.0 : 28


In [189]:
py_list = [0, 1.0, "N", True]
py_list

[0, 1.0, 'N', True]

In [190]:
py_list[0] = 50

In [191]:
py_list[0].bit_length()

6

In [192]:
sys.getsizeof(py_list)

120

In [193]:
i = 0
for x in py_list:
    print(x, ":", sys.getsizeof(py_list[i]))
    i += 1

50 : 28
1.0 : 24
N : 50
True : 28


In [194]:
tuple_ex = tuple(range(1000))
list_ex = list(range(1000))
numpy_ex = np.array([range(1000)])
print("Space taken by tuple =",tuple_ex.__sizeof__()," bytes")
print("Space taken by list =",list_ex.__sizeof__()," bytes")
print("Space taken by NumPy array =",numpy_ex.__sizeof__()," bytes")

Space taken by tuple = 8024  bytes
Space taken by list = 8040  bytes
Space taken by NumPy array = 8128  bytes


In [195]:
import numpy as np
import sys

# a. Create structures
size = 1000000
py_list = list(range(size))
np_array = np.arange(size)

# b. Check memory usage
print("Memory size of Python list:", sys.getsizeof(py_list), "bytes")
print("Memory size of NumPy array:", np_array.nbytes, "bytes")

Memory size of Python list: 8000056 bytes
Memory size of NumPy array: 8000000 bytes


In [196]:
type(py_list[10])

int

In [197]:
py_list[10].bit_length()

4

In [198]:
sys.getsizeof(py_list[10])

28

In [199]:
type(np_array[10])

numpy.int64

In [200]:
np_array[10].nbytes

8

In [201]:
sys.getsizeof(np_array[10])

32

## `numpy.array` Contiguous memory allocation

* NumPy Arrays store data in contiguous blocks of memory, which enhances cache performance and allows for more efficient access and manipulation.

* Python Lists, on the other hand, store references to objects scattered throughout memory, leading to slower access times, especially for large datasets.

* NumPy arrays are generally faster and more efficient for numerical operations compared to Python lists, primarily due to their contiguous memory layout and vectorized operations implemented in optimized C code. 

Question: How many bytes are these elements apart?   
Question: What is the bit size of the data type?

<img src="https://miro.medium.com/v2/resize:fit:1042/1*1sKAFPFUM9LUInN0HCdosQ.jpeg" alt="array_mem_alloc" width="500"> 


## Python `list` memory allocation not contiguous
![python_list_alloc](https://i.sstatic.net/K26b0.png)

In [202]:
py_list = [10, 20, 30, 40, 50]

for i, element in enumerate(py_list):
    print(f"Element {i}: {element}, Memory Address: {id(element)}")

Element 0: 10, Memory Address: 4378749520
Element 1: 20, Memory Address: 4378749840
Element 2: 30, Memory Address: 4378750160
Element 3: 40, Memory Address: 4378750480
Element 4: 50, Memory Address: 4378750800


In [203]:
np_arr = np.array([10,20,30,40,50])

In [204]:
base_address = np_arr.__array_interface__['data'][0]

print("NumPy array memory address:", base_address)

NumPy array memory address: 4939019472


In [205]:
np_arr.dtype

dtype('int64')

In [206]:
element_size = np_arr.itemsize
print(element_size)

8


* 64 bits = 8 bytes

In [207]:
for i in range(len(np_arr)):
    element_address = base_address + i * element_size
    print(f"Element {i}: {np_arr[i]}, Memory Address: {element_address}")

Element 0: 10, Memory Address: 4939019472
Element 1: 20, Memory Address: 4939019480
Element 2: 30, Memory Address: 4939019488
Element 3: 40, Memory Address: 4939019496
Element 4: 50, Memory Address: 4939019504


* 64 bit = 8 bytes 

* Therefore the addresses are 8 bytes apart. 

## 2-Dimensional Arrays

* Need an inner and outer pair of `[ ]` brackets to generate rows and columns. 

* Remember that element access for a Python `list` is `[row][col]` - NOT `[row,col]`

* `numpy.arrays` can use either `[,]` or `[][]` but may need paretheses to in certain contexts where operation is ambigious. 

In [208]:
a = np.array([[1,2,3],[4,5,6]]) 
a


array([[1, 2, 3],
       [4, 5, 6]])

In [209]:
a[1][1]

np.int64(5)

In [210]:
a[1,1]

np.int64(5)

In [211]:
py_2D = [[1,2,3], [4,5,6]]
py_2D

[[1, 2, 3], [4, 5, 6]]

In [212]:
py_2D[1][1]

5

In [213]:
py_2D[1,1]

TypeError: list indices must be integers or slices, not tuple

## `np` array functions

In [215]:
a = np.arange(10) 
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [217]:
py_list = list(range(0,10))
py_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [218]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [219]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [222]:
a = np.ones((3, 2)) 
a


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [224]:
a = np.full([2, 2], 5) 
a


array([[5, 5],
       [5, 5]])

In [226]:
a = np.full((3, 3), 7) 
a


array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [229]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random generation via `numpy.random`

In [241]:
a = np.random.random((2,2)) 
a


array([[0.88737336, 0.4816348 ],
       [0.07973564, 0.84046326]])

In [251]:
a = np.random.randint((1,5)) 
a


array([0, 1])

In [265]:
a = np.random.randint(2, size=10) 
a


array([0, 1, 0, 1, 1, 0, 1, 0, 0, 1])

In [269]:
a = np.random.randint(2, size=(2,2)) 
a


array([[0, 1],
       [0, 0]])

In [271]:
a = np.random.randint(2, size=(2,3)) 
a


array([[0, 0, 1],
       [1, 0, 0]])

In [276]:
a = np.random.randint(9, size=(3,3)) 
a


array([[2, 3, 6],
       [5, 5, 5],
       [7, 2, 6]])

3D arrays! 

In [277]:
a = np.random.randint(9, size=(3,3,3))
a


array([[[6, 3, 1],
        [0, 5, 6],
        [8, 6, 2]],

       [[0, 2, 5],
        [4, 6, 1],
        [6, 7, 8]],

       [[3, 1, 3],
        [3, 5, 2],
        [8, 2, 5]]])

In [279]:
a = np.linspace(0, 1, 11)
a


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Array attributes

* You've already seen: `nbytes` and `dtype` for memory allocation. 

* There are many helpful attributes that describe characteristics of the array for you.

In [281]:
a = np.random.randint(9, size=(3,3))
print("size:", a.size)
print("shape:", a.shape)
print("dimensions:", a.ndim)


size: 9
shape: (3, 3)
dimensions: 2


In [283]:
a = np.random.randint(9, size=(3,3,3))
print("size:", a.size)
print("shape:", a.shape)
print("dimensions:", a.ndim)

size: 27
shape: (3, 3, 3)
dimensions: 3


In [284]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

## Array slicing `[ : ]`

* `array_name[ start : stop : interval]`

In [285]:
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [286]:
print(a[3])


3


In [102]:
a[:3]


array([0, 1, 2])

In [287]:
a[3:]


array([3, 4, 5, 6, 7, 8, 9])

In [288]:
a[3:6]


array([3, 4, 5])

Steps/intervals of 2:

In [289]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [294]:
a[3:6:2]


array([3, 5])

Mutiples of 3

In [296]:
a[::3]


array([0, 3, 6, 9])

## Row and Col access

In [298]:
a = np.random.randint(9, size=(3,3)) 
a


array([[1, 3, 4],
       [0, 4, 7],
       [0, 7, 7]])

All of the first column (column 0) - displayed in a one-dimensional form

In [299]:
a[:,0]


array([1, 0, 0])

All of the first row (row 0)

In [301]:
a[0,:]


array([1, 3, 4])

All of the second row (row 1)

In [303]:
a[1,:]


array([0, 4, 7])

## Iteration vs Vectorisation

* Vectorisation is a mathmatical transformation from a matrix to a column vector. 

* `numpy` arrays can leverage this ability, allowing operations to be performed on entire arrays without explicit Python loops, and are instead implemented in optimised C and Fortran code 'behind the scenes'.

* Essentially, this allows for parallel processing, rather than sequential / iterative processing.

* Python `lists` require explicit loops or list comprehensions for element-wise operations, which are executed in the slower Python interpreter.


In [304]:
import numpy as np
import time
import timeit

Scenario: Multiply $a$ and $b$ element-wise

```
1 * 4 = 4
2 * 5 = 10
3 * 6 = 18
      +
  sum = 32
```

In [305]:
a = np.array([1,2,3])
b = np.array([4,5,6])

Vectorised operation on `numpy arrays`

In [306]:
c = np.sum(a * b)
print(c)

32


In [307]:
print(np.matmul(a,b))

32


Attempting vectorisation on python `lists` - you'll see that the below won't work, as `lists` are not vectorised.

In [308]:
a = [1,2,3]
b = [4,5,6]

c = sum(a * b)

print(c)

TypeError: can't multiply sequence by non-int of type 'list'

Therefore, for lists, we have to revert to a non-vectorised (iterative) approach

In [309]:
a = [1,2,3]
b = [4,5,6]

c = 0
for i in range(len(a)):
    c += a[i] * b[i]
print(c)

32


## Matrix Multiplication


In [310]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [311]:
a

array([[1, 2],
       [3, 4]])

In [106]:
b

array([[5, 6],
       [7, 8]])

![mat_mul](https://www.geeksforgeeks.org/wp-content/uploads/strassen_new.png)

In [312]:
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

In [313]:
a @ b

array([[19, 22],
       [43, 50]])

In [314]:
c = np.sum(a * b)
print(c)

70


Python 2D list, by contrast...

In [323]:
a_l = [[1,2,3], [3,4,5], [6,7,8]]
b_l = [[5,6,7], [7,8,9], [4,5,6]]

In [324]:
a_l

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]

In [325]:
b_l

[[5, 6, 7], [7, 8, 9], [4, 5, 6]]

In [326]:
c_l = a_l #for shape
for x in range(len(a_l)):
    for y in range(len(b_l)):
        c[x][y] = (a_l[x][y] * b_l[x][y])
c_l

IndexError: invalid index to scalar variable.

It's also easier to multiply unequally sized 2D arrays with Numpy: 


In [327]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [328]:
b = np.array([[3,4], [5,6], [7,8]])
b

array([[3, 4],
       [5, 6],
       [7, 8]])

![martix_mult_dot](https://miro.medium.com/v2/resize:fit:1200/0*NACYO5_4KyxEZvOF.gif)

In [329]:
np.dot(a,b)

array([[34, 40],
       [79, 94]])

In [330]:
np.matmul(a,b)

array([[34, 40],
       [79, 94]])

## An image is an matrix of values

![mnist_matrix](https://www.researchgate.net/publication/370634232/figure/fig2/AS:11431281157036794@1683688795769/Matrix-values-for-a-sample-of-number-3-in-MNIST-6.jpg)

## Let's time these operations

In [331]:
size = 1000000

py_list = list(range(size))
np_array = np.arange(size)

In [334]:
def list_addition(py_list):
    return [x + 1 for x in py_list]

start_time = time.time()
list_result = list_addition(py_list)
py_add_time = time.time() - start_time
print(f"Python List Addition Time: {py_add_time:.6f} seconds")

Python List Addition Time: 0.050311 seconds


In [335]:
def numpy_addition(np_array):
    return np_array + 1

start_time = time.time()
array_result = numpy_addition(np_array)
np_add_time = time.time() - start_time
print(f"Numpy Array Addition Time: {np_add_time:.6f} seconds")

Numpy Array Addition Time: 0.002742 seconds


In [336]:
def list_multiplication(py_list):
    return [x * 2 for x in py_list]

start_time = time.time()
list_mul_result = list_multiplication(py_list)
py_mul_time = time.time() - start_time
print(f"Python List Multiplication Time: {py_mul_time:.6f} seconds")

Python List Multiplication Time: 0.156458 seconds


In [337]:
def numpy_multiplication(np_array):
    return np_array * 2

start_time = time.time()
array_mul_result = numpy_multiplication(np_array)
np_mul_time = time.time() - start_time
print(f"Numpy Array Multiplication Time: {np_mul_time:.6f} seconds")

Numpy Array Multiplication Time: 0.006014 seconds


In [338]:
def list_sum(py_list):
    return sum(py_list)

def list_mean(py_list):
    return sum(py_list) / len(py_list)

start_time = time.time()
list_sum_result = list_sum(py_list)
list_mean_result = list_mean(py_list)
py_agg_time = time.time() - start_time
print(f"Python List Sum and Mean Time: {py_agg_time:.6f} seconds")

Python List Sum and Mean Time: 0.015899 seconds


In [339]:
def numpy_sum(np_array):
    return np.sum(np_array)

def numpy_mean(np_array):
    return np.mean(np_array)

start_time = time.time()
array_sum_result = numpy_sum(np_array)
array_mean_result = numpy_mean(np_array)
np_agg_time = time.time() - start_time
print(f"Numpy Array Sum and Mean Time: {np_agg_time:.6f} seconds")

Numpy Array Sum and Mean Time: 0.003389 seconds


In [340]:
import numpy as np
import statistics
import time

# Create a NumPy array and a Python list
data_size = 1000000
np_array = np.random.rand(data_size)
py_list = np_array.tolist()

# a. NumPy aggregation
start_time = time.time()
np_sum = np_array.sum()
np_mean = np_array.mean()
np_std = np_array.std()
np_time = time.time() - start_time
print("Numpy - Sum:", np_sum, "Mean:", np_mean, "Std Dev:", np_std)
print("Numpy Aggregation Time:", np_time, "seconds")

# b. Python list aggregation
start_time = time.time()
py_sum = sum(py_list)
py_mean = py_sum / len(py_list)
py_std = statistics.stdev(py_list)
py_time = time.time() - start_time
print("Python List - Sum:", py_sum, "Mean:", py_mean, "Std Dev:", py_std)
print("Python List Aggregation Time:", py_time, "seconds")

Numpy - Sum: 500050.1030227136 Mean: 0.5000501030227136 Std Dev: 0.2884588334221624
Numpy Aggregation Time: 0.0024089813232421875 seconds
Python List - Sum: 500050.1030227348 Mean: 0.5000501030227348 Std Dev: 0.28845897765168727
Python List Aggregation Time: 1.1484520435333252 seconds


In [341]:
import numpy as np

# a. NumPy array and Python list
np_array = np.array([1, 2, 3])
py_list = [4, 5, 6]

# Concatenate using np.concatenate
combined = np.concatenate((np_array, py_list))
print("Combined with np.concatenate:", combined)
print("Data type:", combined.dtype)

# Alternative: Extend the list with array
py_list_extended = py_list.copy()
py_list_extended.extend(np_array)
print("List extended with NumPy array:", py_list_extended)
print("Data types in extended list:", [type(x) for x in py_list_extended])

Combined with np.concatenate: [1 2 3 4 5 6]
Data type: int64
List extended with NumPy array: [4, 5, 6, np.int64(1), np.int64(2), np.int64(3)]
Data types in extended list: [<class 'int'>, <class 'int'>, <class 'int'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>]


## Broadcasting with `numpy.array`

* Broadcast = like 'send message to all' - apply to all elements

* Useful to apply operations to unequal sizes of array/matrix

![numpy_broadcast](https://www.w3resource.com/w3r_images/python-numpy-exercise-124.svg)

In [342]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([10,20,30]) 

In [343]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [344]:
b

array([10, 20, 30])

In [345]:
c = a + b
c

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

## Boolean Masking with `numpy.array`

* Boolean = True or False

* Masking = like a 'mask layer' in Photoshop, this gives you a 'view' of the structure, based on whether it fulfils the condition set (the mask)

In [346]:
c

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [348]:
mask = (c > 20)
mask 


array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

## Summary - `numpy.array` vs Python `list`

`numpy.array` is useful when:
* Performing numerical computations on large datasets.
* Needing to leverage vectorized operations for performance.
* Requiring efficient memory usage.

The Python `list` is useful when:
* Dealing with heterogeneous data types.
* Performing operations that require dynamic resizing.
* Managing data that doesn’t require intensive numerical computations.

![py_list_vs_numpy](https://i.sstatic.net/K26b0.png)

## Exercise 

Create an array of all the even integers from 10 to 50.  
Remember to `import numpy as np` (if you haven't run any code cells above).

In [ ]:
# Write your solution here. 


## Exercise 

Compare `list(range())` function with `np.arange()`. Create both a Python list and a Numpy array with values `[0,1,2,3,4,5,6,7,8,9]`. What are the data types by default?

In [ ]:
# Write your solution here. 


## Exercise 

Create a one-dimensional numpy array of 50 random integers between 0-9. Furthemore, specify the integers to be of `numpy.int8` type to save space. Check to see whether the elements are stored 1 byte apart (8 bits).

In [ ]:
# Write your solution here. 


## Exercise 

You may have written a function in a previous notebook which will rotate any given list by a specified given number of positions $n$. 

For example: if you had the list `[6, 7, 8, 9, 10]` and this was required to be rotated by 2 positions, the output would be `[8, 9, 10, 6, 7]`. 

If you wrote a function for a list, see if this works for a numpy array. If not, how would you modify your algorithm to work for a numpy array? 

In [ ]:
# Write your solution here.

## Exercise 

Perform element-wise operations on an `numpy.array` of 50 elements. For example, add 5 to each of the elements. Now compare this with the same approach applied to an equivalent Python `list` of 50 elements. Do they operate in the same way? 

In [ ]:
# Write your solution here. 


## Exercise 

Now time how long it takes to perform element-wise addition on a python `list` and `numpy.array` of 1,000,000 elements assigned integers randomly assigned values between 0-9. 

Can this operation be performed faster on one data structure than the other? If so, why? 

In [ ]:
# Write your solution here. 


## Exercise: 

You may have written a function to reverse the contents of a python `str` or `list` in previous notebooks. Can you use this same function with a `numpy.array`? 

Extension: if you've used any library functions to achieve the reversal of the data structure, how would you do this operation manually (without any library functions)? 


In [ ]:
# Write your solution here.


## Exercise 

Now create a one dimensional numpy array with 64 elements. Initialise these to empty characters (empty `str` in Python). Then `reshape` this one-dimensional array into an 8 x 8 two-dimensional array.  

In [ ]:
# Write your solution here. 


## Scenario Exercise - Chess Board

<img src="https://lh3.googleusercontent.com/proxy/REMapHsJd3Wf2rVl5OLw8tYsjEJRcDeOqlh2io-YvuIboUZXn_1flhYeuiKDGXpfkr4ADD_2DBXlpp6bEkA-j7ueo1AP12ijDeVhLZXhudwGEM6gJ67QikCgccSmyk7sBL0" alt="knight_chess" width="250"> 

Write a function that would move a knight chess piece to a given space on a chess board. Remember that knights move in an L shape. Two spaces then one space. 

To simulate this, add a 'K' character to any position in your 8 x 8 two-dimensional array, and apply your function. 

To start with, choose one of moves and focus on getting this right. Then start to add more possible moves. Perhaps you could let the user select which grid coordinate they want to move to?


In [ ]:
# Write your solution here. 


## Exercise 

As you can see from the image of the chess board above, the squares alternate in colour - white and grey. 

Can you write an algorithm to colour the squares of your 8 x 8 `numpy.array` like this? 

Extension: What if each of the 64 squares were 8 x 8 pixels? How would you amend your algorithm to colour alternate squares? 

In [ ]:
# Write your solution here. 


## Extension (Scenario exercise): Web Chess

Can you draw this chess board in Flask, using your `numpy.array`?

Extension: How about populating the board with pieces? 

Extension 2: How about asking a player to make a move? 

<img src="https://www.regencychess.co.uk/images/how-to-set-up-a-chessboard/how-to-set-up-a-chessboard-7.jpg" alt="chess_board" width="250"> 


In [ ]:
# Best to write your solution in your Flask template, using py scripts.


## Additional Matrix (2D Array) Exercises


## Exercise 

Perform matrix multiplication of two 2D `numpy.arrays` of the same size $N$ x $N$ (e.g. two 5 x 5 arrays). Check the multiplication has been performed element-wise. 

Can you use this same algorithm for 2D python `lists`? 

In [ ]:
# Write your solution here. 


## Exercise 

Write an algorithm such that if an element in an $M$ x $N$ matrix is 0, its entire row and column are set to 0. 

In [ ]:
# Write your solution here.


## Exercise: 

Given an image represented by an $N$ x $N$ matrix, where each pixel in the image is 4 bytes, write a function to rotate the image by 90 degrees. 

Extension: Can you do this in place? (without additional data structures)

In [ ]:
# Write your solution here. 
