# 03 Numpy 


## Plan for this lecture

1. Numpy Introduction 

2. Contrast Array and Python List 

3. 

## Introduction to Numpy 

![numpy_logo](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/320px-NumPy_logo_2020.svg.png)
* Numerical Python (NumPy) is a package full of methods that can perform useful operations on data.  

* NumPy provides a convenient API (Application Programmable Interface) that provides a way to ‘interface’ with / operate on data. 

* It reintroduces types which is more coding but more efficient way to search/sort/store data than the ‘loosely’ typed nature of Python that we’ve seen so far. 

* More documentation available at: https://numpy.org 


## Numpy Arrays vs Python List

* NumPy arrays are different to Python Lists. 

* NumPy arrays reintroduce the ‘typed’ nature of more ‘verbose’ languages (C, C++, Java), where everything is explicitly typed. 

* NumPy arrays operate like arrays from C and Java where they declared to store data of one type (only integers), unlike Python and JS, which can store data of different types. 

* NumPy arrays therefore data is ‘cast’ – floating point numbers to integers, or in some cases – an error is produced (strings to integers).

## Getting started with Numpy

* You'll either need to install this if you're in VSC. 

* OR if you're in Anaconda or Google Colab, you should have access to it already...

`pip install numpy`

`python3 -m pip install -U numpy --user`

In [1]:
import numpy as np 
np

<module 'numpy' from '/Users/nick/Library/Python/3.9/lib/python/site-packages/numpy/__init__.py'>

In [76]:
a = np.array([1,2,3,4,5,6]) 
a


array([1, 2, 3, 4, 5, 6])

## Upcasting to floating points

Notice below how one floating point number will upcast all the integers to floats

In [77]:
a = np.array([3.14,2,3,4,5]) 
a


array([3.14, 2.  , 3.  , 4.  , 5.  ])

In [78]:
a = np.array([1,2,3],dtype='float32')
a


array([1., 2., 3.], dtype=float32)

## 2-Dimensions!

In [79]:
a = np.array([[1,2,3],[4,5,6]]) 
a


array([[1, 2, 3],
       [4, 5, 6]])

## Array functions

In [80]:
a = np.arange(3) 
a


array([0, 1, 2])

In [81]:
a = np.arange(10) 
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [82]:
a = np.ones((3, 2)) 
a


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [83]:
a = np.full((2, 2), 5) 
a


array([[5, 5],
       [5, 5]])

In [84]:
a = np.full((3, 3), 7) 
a


array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random

In [85]:
a = np.random.random((2,2)) 
a


array([[0.64254536, 0.71292754],
       [0.27729644, 0.96306581]])

In [86]:
a = np.random.randint((2,2)) 
a


array([0, 1])

In [87]:
a = np.random.randint(2, size=10) 
a


array([1, 1, 1, 1, 0, 1, 0, 0, 1, 0])

In [88]:
a = np.random.randint(2, size=(2,2)) 
a


array([[1, 0],
       [1, 1]])

In [89]:
a = np.random.randint(2, size=(3,2)) 
a


array([[1, 0],
       [1, 0],
       [1, 0]])

In [90]:
a = np.random.randint(2, size=(2,3)) 
a


array([[0, 1, 0],
       [1, 1, 0]])

In [91]:
a = np.random.randint(3, size=(3,3)) 
a


array([[1, 2, 2],
       [1, 2, 1],
       [0, 2, 1]])

In [92]:
a = np.random.randint(9, size=(3,3)) 
a


array([[8, 0, 1],
       [3, 7, 6],
       [8, 2, 8]])

In [93]:
a = np.random.randint(9, size=(3,3,3))
a


array([[[5, 4, 6],
        [6, 6, 6],
        [4, 8, 4]],

       [[2, 6, 8],
        [4, 4, 6],
        [7, 8, 0]],

       [[0, 8, 5],
        [4, 7, 3],
        [2, 7, 1]]])

In [94]:
a = np.linspace(0, 1, 11)
a


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Array attributes

In [95]:
a = np.random.randint(9, size=(3,3))
print("size:", a.size)
print("shape:", a.shape)
print("dimensions:", a.ndim)


size: 9
shape: (3, 3)
dimensions: 2


In [96]:
a = np.random.randint(9, size=(3,3,3))
print("size:", a.size)
print("shape:", a.shape)
print("dimensions:", a.ndim)

size: 27
shape: (3, 3, 3)
dimensions: 3


## Array slicing `[ : ]`

* `array_name[ start : stop : interval]`

In [97]:
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
print(a[3])


3


In [102]:
a[:3]


array([0, 1, 2])

In [103]:
a[3:]


array([3, 4, 5, 6, 7, 8, 9])

In [104]:
a[3:6]


array([3, 4, 5])

Steps/intervals of 2:

In [105]:
a[3:6:2]


array([3, 5])

Mutiples of 3

In [106]:
a[::3]


array([0, 3, 6, 9])

## Row and Col access

In [107]:
a = np.random.randint(9, size=(3,3)) 
a


array([[2, 0, 5],
       [5, 2, 3],
       [6, 1, 1]])

All of the first column (column 0) - displayed in a one-dimensional form

In [112]:
a[:,0]


array([2, 5, 6])

All of the first row (row 0)

In [113]:
a[0,:]


array([2, 0, 5])

All of the second row (row 1)

In [114]:
a[1,:]


array([5, 2, 3])

## Exercises 

#### 1. Import NumPy as np

#### 2. Create an array of 10 zeros 

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 4. Create an array of 10 fives

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### 5. Create an array of the integers from 10 to 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Create an array of all the even integers from 10 to 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Use NumPy to generate a random number between 0 and 1

array([ 0.42829726])

#### 10. Use NumPy to generate an array of 25 random numbers

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Exercise 4: 

Without using any functions provided by libraries (e.g. `reverse()`), implement a function that will reverse the contents of a string. 


## Exercise 5
Write a function to determine if a string has all unique characters.

Extension: What if you cannot use additional data structures?

## Exercise 6: 

Write a function that will replace all spaces in a string with "%20". This is the hexedecimal encoding that is used to replace spaces in URLs (which cannot contain spaces). 

## Exercise 6: 
Given two strings, write a function to decide if one is a permutation of the other. 

## Exercise 7: 
Given an image represented by an NxN matrix, where each pixel in the image is 4 bytes, write a function to rotate the image by 90 degrees. 

Extension: Can you do this in place? (without additional data structures)